server:
  port: 9981

spring:
  profiles:
    active: dev #默认为开发环境
  jackson:
    date-format: yyyy-MM-dd #时间格式
  main:
    allow-bean-definition-overriding: true
mybatis:
  mapper-locations:
    - classpath*:com/**/dao/*.xml
    - classpath*:com/**/mapper/*.xml


redis:
  database: blog
  key:
    mcmanager: 'bc:manager'
    mcresourceList: 'bc:resourceList'
  expire:
    common: 86400 # 24小时

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: blog-cms #JWT加解密使用的密钥
  expiration: 2592000 #JWT的超期限时间(60*60*24*30)
  tokenHead: Bearer  #JWT负载中拿到开头

secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /cms/manager/login


logging:
  level:
    root: info #日志配置DEBUG,INFO,WARN,ERROR
    com.carroll.blog: debug
#  file: demo_log.log #配置日志生成路径
#  path: /var/logs #配置日志文件名称

