spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: tiger
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
redis:
  host: localhost # Redis服务器地址
  database: 0 # Redis数据库索引（默认为0）
  port: 6379 # Redis服务器连接端口
  password: # Redis服务器连接密码（默认为空）
  timeout: 300ms # 连接超时时间（毫秒）
aliyun:
  oss:
    endpoint: http://oss-cn-shanghai.aliyuncs.com # oss对外服务的访问域名
    accessKeyId: LTAIl3E22d3VNryb # 访问身份验证中用到用户标识
    accessKeySecret: ePOjk9X5iASO5lU3OI8N9hiYCL5zDA # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: aep-xyz # oss的存储空间